# Docker Compose configuration for QuickFixAI project
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://frontend:80

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=http://backend:3001
